---
- name: Setup fit-ctf playground
  hosts: playground
  vars:
    user: user
    repo_url: https://github.com/hungdojan/fit-ctf
    repo_dir: /opt/fit-ctf
    rdz_port: 5555
    node_exporter_port: 9100
  roles:
    - fit-ctf
    - node-exporter
