name: fit-ctf-playground
type: virtual-machine
profiles:
  - default
source:
  alias: rockylinux/10/default
  mode: pull
  protocol: simplestreams
  server: https://images.linuxcontainers.org
  type: image
devices:
  eth0:
    ipv4.address: 10.100.0.21
    name: eth0
    network: fitctfbr0
    type: nic
  root:
    path: /
    pool: fit-ctf-pool
    type: disk
    size: 30GiB
config:
  boot.autostart: true
  limits.cpu: '1'
  limits.memory: '1536MiB'
